"""
Teeworlds 0.7 Protocol Constants

Network protocol constants, message IDs, and game configuration values.
Based on: https://github.com/teeworlds/teeworlds/blob/master/datasrc/network.py
"""

# Protocol version
NET_VERSION = 2

# Packet sizes
NET_MAX_PACKETSIZE = 1400
NET_MAX_PAYLOAD = NET_MAX_PACKETSIZE - 6
NET_MAX_CHUNKHEADERSIZE = 5
NET_PACKETHEADERSIZE = 3
NET_MAX_CLIENTS = 64
NET_MAX_SEQUENCE = 1 << 10
NET_SEQUENCE_MASK = NET_MAX_SEQUENCE - 1

# Connection states
NET_CONNSTATE_OFFLINE = 0
NET_CONNSTATE_CONNECT = 1
NET_CONNSTATE_PENDING = 2
NET_CONNSTATE_ONLINE = 3
NET_CONNSTATE_ERROR = 4

# Packet flags
NET_PACKETFLAG_CONTROL = 1
NET_PACKETFLAG_CONNLESS = 2
NET_PACKETFLAG_RESEND = 4
NET_PACKETFLAG_COMPRESSION = 8
NET_PACKETFLAG_EXTENDED = 16

# Chunk flags
NET_CHUNKFLAG_VITAL = 1
NET_CHUNKFLAG_RESEND = 2

# Control messages
NET_CTRLMSG_KEEPALIVE = 0
NET_CTRLMSG_CONNECT = 1
NET_CTRLMSG_CONNECTACCEPT = 2
NET_CTRLMSG_ACCEPT = 3
NET_CTRLMSG_CLOSE = 4

# Security token
SECURITY_TOKEN_MAGIC = b"TKEN"
NET_SECURITY_TOKEN_UNKNOWN = -1
NET_SECURITY_TOKEN_UNSUPPORTED = 0

# Buffer sizes
NET_CONN_BUFFERSIZE = 1024 * 32
PACKER_BUFFER_SIZE = 1024 * 2

# =============================================================================
# System messages (sent with sys=True)
# =============================================================================

NETMSG_INVALID = 0
NETMSG_INFO = 1
NETMSG_MAP_CHANGE = 2
NETMSG_MAP_DATA = 3
NETMSG_CON_READY = 4
NETMSG_SNAP = 5
NETMSG_SNAPEMPTY = 6
NETMSG_SNAPSINGLE = 7
NETMSG_SNAPSMALL = 8
NETMSG_INPUTTIMING = 9
NETMSG_RCON_AUTH_STATUS = 10
NETMSG_RCON_LINE = 11
NETMSG_AUTH_CHALLANGE = 12
NETMSG_AUTH_RESULT = 13
NETMSG_READY = 14
NETMSG_ENTERGAME = 15
NETMSG_INPUT = 16
NETMSG_RCON_CMD = 17
NETMSG_RCON_AUTH = 17
NETMSG_REQUEST_MAP_DATA = 18
NETMSG_AUTH_START = 19
NETMSG_AUTH_RESPONSE = 20
NETMSG_PING = 21
NETMSG_PING_REPLY = 22
NETMSG_ERROR = 23
NETMSG_RCON_CMD_ADD = 24
NETMSG_RCON_CMD_REM = 25

# =============================================================================
# Game messages (sent with sys=False)
# =============================================================================

NETMSGTYPE_INVALID = 0
NETMSGTYPE_SV_MOTD = 1
NETMSGTYPE_SV_BROADCAST = 2
NETMSGTYPE_SV_CHAT = 3
NETMSGTYPE_SV_KILLMSG = 4
NETMSGTYPE_SV_SOUNDGLOBAL = 5
NETMSGTYPE_SV_TUNEPARAMS = 6
NETMSGTYPE_SV_EXTRAPROJECTILE = 7
NETMSGTYPE_SV_READYTOENTER = 8
NETMSGTYPE_SV_WEAPONPICKUP = 9
NETMSGTYPE_SV_EMOTICON = 10
NETMSGTYPE_SV_VOTECLEAROPTIONS = 11
NETMSGTYPE_SV_VOTEOPTIONLISTADD = 12
NETMSGTYPE_SV_VOTEOPTIONADD = 13
NETMSGTYPE_SV_VOTEOPTIONREMOVE = 14
NETMSGTYPE_SV_VOTESET = 15
NETMSGTYPE_SV_VOTESTATUS = 16
NETMSGTYPE_CL_SAY = 17
NETMSGTYPE_CL_SETTEAM = 18
NETMSGTYPE_CL_SETSPECTATORMODE = 19
NETMSGTYPE_CL_STARTINFO = 20
NETMSGTYPE_CL_CHANGEINFO = 21
NETMSGTYPE_CL_KILL = 22
NETMSGTYPE_CL_EMOTICON = 23
NETMSGTYPE_CL_VOTE = 24
NETMSGTYPE_CL_CALLVOTE = 25

# =============================================================================
# Snapshot object types
# =============================================================================

NETOBJTYPE_INVALID = 0
NETOBJTYPE_PLAYERINPUT = 1
NETOBJTYPE_PROJECTILE = 2
NETOBJTYPE_LASER = 3
NETOBJTYPE_PICKUP = 4
NETOBJTYPE_FLAG = 5
NETOBJTYPE_GAMEDATA = 6
NETOBJTYPE_GAMEDATATEAM = 7
NETOBJTYPE_GAMEDATAFLAG = 8
NETOBJTYPE_CHARACTERCORE = 9
NETOBJTYPE_CHARACTER = 10
NETOBJTYPE_PLAYERINFO = 11
NETOBJTYPE_SPECTATORINFO = 12

# Event types (also in snapshots)
NETEVENTTYPE_COMMON = 13
NETEVENTTYPE_EXPLOSION = 14
NETEVENTTYPE_SPAWN = 15
NETEVENTTYPE_HAMMERHIT = 16
NETEVENTTYPE_DEATH = 17
NETEVENTTYPE_SOUNDWORLD = 18
NETEVENTTYPE_DAMAGE = 19

# Snapshot object sizes (in ints)
NETOBJ_SIZES = {
    NETOBJTYPE_PLAYERINPUT: 10,
    NETOBJTYPE_PROJECTILE: 6,
    NETOBJTYPE_LASER: 5,
    NETOBJTYPE_PICKUP: 3,
    NETOBJTYPE_FLAG: 3,
    NETOBJTYPE_GAMEDATA: 3,
    NETOBJTYPE_GAMEDATATEAM: 2,
    NETOBJTYPE_GAMEDATAFLAG: 4,
    NETOBJTYPE_CHARACTERCORE: 15,
    NETOBJTYPE_CHARACTER: 22,  # CharacterCore (15) + Character extension (7)
    NETOBJTYPE_PLAYERINFO: 3,
    NETOBJTYPE_SPECTATORINFO: 4,
}

# =============================================================================
# Game configuration
# =============================================================================

SERVER_TICK_SPEED = 50  # 50 ticks per second

# Teams
TEAM_SPECTATORS = -1
TEAM_RED = 0
TEAM_BLUE = 1

# Weapons
WEAPON_HAMMER = 0
WEAPON_GUN = 1
WEAPON_SHOTGUN = 2
WEAPON_GRENADE = 3
WEAPON_LASER = 4
WEAPON_NINJA = 5
NUM_WEAPONS = 6

# Weapon names
WEAPON_NAMES = {
    WEAPON_HAMMER: "Hammer",
    WEAPON_GUN: "Gun",
    WEAPON_SHOTGUN: "Shotgun",
    WEAPON_GRENADE: "Grenade",
    WEAPON_LASER: "Laser",
    WEAPON_NINJA: "Ninja",
}

# Pickups
PICKUP_HEALTH = 0
PICKUP_ARMOR = 1
PICKUP_GRENADE = 2
PICKUP_SHOTGUN = 3
PICKUP_LASER = 4
PICKUP_NINJA = 5
PICKUP_GUN = 6
PICKUP_HAMMER = 7

# Player flags
PLAYERFLAG_ADMIN = 1 << 0
PLAYERFLAG_CHATTING = 1 << 1
PLAYERFLAG_SCOREBOARD = 1 << 2
PLAYERFLAG_READY = 1 << 3
PLAYERFLAG_DEAD = 1 << 4
PLAYERFLAG_WATCHING = 1 << 5
PLAYERFLAG_BOT = 1 << 6

# Game state flags
GAMESTATEFLAG_WARMUP = 1 << 0
GAMESTATEFLAG_SUDDENDEATH = 1 << 1
GAMESTATEFLAG_ROUNDOVER = 1 << 2
GAMESTATEFLAG_GAMEOVER = 1 << 3
GAMESTATEFLAG_PAUSED = 1 << 4
GAMESTATEFLAG_STARTCOUNTDOWN = 1 << 5

# Hook states
HOOK_RETRACTED = -1
HOOK_IDLE = 0
HOOK_RETRACT_START = 1
HOOK_RETRACT_END = 3
HOOK_FLYING = 4
HOOK_GRABBED = 5

# Max values
MAX_CLIENTS = 64
MAX_NAME_LENGTH = 16
MAX_CLAN_LENGTH = 12
MAX_INPUT_SIZE = 128
MAX_SNAPSHOT_PACKSIZE = 900

# Input state mask
INPUT_STATE_MASK = 0x3F

# Net version string (0.7 format)
NET_VERSION_STR = "0.7 802f1be60a05665f"
